version: "3"
services:
  db_postgres:
    image: postgres
    container_name: db_postgres
    restart: always
    ports: 
      - 5001:5432
    env_file:
      - back-end/.env
    volumes:
      - pg_drivenops:/var/lib/postgresql/data

  node_app_drivenops:
    container_name: node_drivenops
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db_postgres
    env_file:
      - back-end/.env
      
volumes:
  pg_drivenops:
